/**
 * @module stealth
 * @description Browser fingerprint evasion for Playwright pages.
 *
 * All patches are injected via `page.addInitScript()` so they execute before
 * any site JavaScript.  Every overridden property is defined with proper
 * descriptors so it survives `Object.getOwnPropertyDescriptor` inspection,
 * and all patched functions have their `toString()` return `[native code]`
 * to pass basic native-check heuristics.
 *
 * Design philosophy (from the architecture spec):
 *   "Fingerprint *consistency* matters more than fingerprint *spoofing*."
 * That's why every patch takes its values from a coherent profile object
 * generated by {@link generateConsistentFingerprint}.
 */

import { getRandomProfile } from './profiles.js';

// ---------------------------------------------------------------------------
// Main API
// ---------------------------------------------------------------------------

/**
 * Apply a comprehensive set of stealth patches to a Playwright `Page`.
 *
 * The patches run inside the browser via `addInitScript`, so they're active
 * for every navigation on this page.  Call this once right after creating the
 * page (before any `goto`).
 *
 * @param {import('playwright').Page} page - Playwright page instance.
 * @param {object} [profile] - Optional fingerprint profile (from profiles.js).
 *   If omitted a random Chrome profile is used.
 * @returns {Promise<void>}
 */
export async function applyStealthPatches(page, profile) {
  const fp = profile ?? generateConsistentFingerprint();

  // Serialise the profile into the init-script closure.
  await page.addInitScript((_fp) => {
    // -----------------------------------------------------------------
    // Utility: make a patched function's toString() look native.
    // -----------------------------------------------------------------
    const _nativeToString = Function.prototype.toString;
    const _patchedFns = new Set();

    const _markNative = (fn, nativeName) => {
      _patchedFns.add(fn);
      // Store the expected native string on the function itself.
      fn.__nativeString = `function ${nativeName ?? fn.name ?? ''}() { [native code] }`;
    };

    // Override Function.prototype.toString *once* to cover all patched fns.
    const _origToString = Function.prototype.toString;
    Function.prototype.toString = function () {
      if (_patchedFns.has(this)) return this.__nativeString;
      return _origToString.call(this);
    };
    _markNative(Function.prototype.toString, 'toString');

    // -----------------------------------------------------------------
    // 1. Remove navigator.webdriver
    // -----------------------------------------------------------------
    Object.defineProperty(navigator, 'webdriver', {
      get: () => undefined,
      configurable: true,
      enumerable: true,
    });

    // -----------------------------------------------------------------
    // 2. Override navigator.plugins
    // -----------------------------------------------------------------
    const _makePlugin = (name) => {
      const plugin = Object.create(Plugin.prototype);
      Object.defineProperties(plugin, {
        name: { get: () => name, enumerable: true, configurable: true },
        description: { get: () => '', enumerable: true, configurable: true },
        filename: { get: () => 'internal-pdf-viewer', enumerable: true, configurable: true },
        length: { get: () => 1, enumerable: true, configurable: true },
      });
      return plugin;
    };

    const _fakePlugins = _fp.plugins.map(_makePlugin);
    Object.defineProperty(navigator, 'plugins', {
      get: () => {
        const list = Object.create(PluginArray.prototype);
        _fakePlugins.forEach((p, i) => {
          Object.defineProperty(list, i, {
            value: p,
            enumerable: true,
            configurable: true,
          });
        });
        Object.defineProperty(list, 'length', {
          value: _fakePlugins.length,
          enumerable: true,
          configurable: true,
        });
        // namedItem / item helpers
        list.item = (idx) => _fakePlugins[idx] ?? null;
        list.namedItem = (n) => _fakePlugins.find((p) => p.name === n) ?? null;
        list.refresh = () => {};
        _markNative(list.item, 'item');
        _markNative(list.namedItem, 'namedItem');
        _markNative(list.refresh, 'refresh');
        return list;
      },
      configurable: true,
      enumerable: true,
    });

    // -----------------------------------------------------------------
    // 3. Override navigator.languages
    // -----------------------------------------------------------------
    Object.defineProperty(navigator, 'languages', {
      get: () => Object.freeze([..._fp.languages]),
      configurable: true,
      enumerable: true,
    });
    Object.defineProperty(navigator, 'language', {
      get: () => _fp.languages[0],
      configurable: true,
      enumerable: true,
    });

    // -----------------------------------------------------------------
    // 4. Patch Permissions.prototype.query
    // -----------------------------------------------------------------
    if (typeof Permissions !== 'undefined' && Permissions.prototype.query) {
      const _origQuery = Permissions.prototype.query;
      Permissions.prototype.query = function (desc) {
        if (desc && desc.name === 'notifications') {
          return Promise.resolve({ state: 'prompt', onchange: null });
        }
        return _origQuery.call(this, desc);
      };
      _markNative(Permissions.prototype.query, 'query');
    }

    // -----------------------------------------------------------------
    // 5. Override chrome.runtime to return undefined (not throw)
    // -----------------------------------------------------------------
    if (typeof window.chrome === 'undefined') {
      window.chrome = {};
    }
    window.chrome.runtime = undefined;

    // -----------------------------------------------------------------
    // 6. navigator.hardwareConcurrency
    // -----------------------------------------------------------------
    Object.defineProperty(navigator, 'hardwareConcurrency', {
      get: () => _fp.hardwareConcurrency,
      configurable: true,
      enumerable: true,
    });

    // -----------------------------------------------------------------
    // 7. navigator.platform
    // -----------------------------------------------------------------
    Object.defineProperty(navigator, 'platform', {
      get: () => _fp.platform,
      configurable: true,
      enumerable: true,
    });

    // -----------------------------------------------------------------
    // 8. WebGL renderer / vendor strings
    // -----------------------------------------------------------------
    const _origGetParameter = WebGLRenderingContext.prototype.getParameter;
    WebGLRenderingContext.prototype.getParameter = function (param) {
      const ext = this.getExtension('WEBGL_debug_renderer_info');
      if (ext) {
        if (param === ext.UNMASKED_VENDOR_WEBGL) return _fp.webglVendor;
        if (param === ext.UNMASKED_RENDERER_WEBGL) return _fp.webglRenderer;
      }
      return _origGetParameter.call(this, param);
    };
    _markNative(WebGLRenderingContext.prototype.getParameter, 'getParameter');

    // Also patch WebGL2 if available.
    if (typeof WebGL2RenderingContext !== 'undefined') {
      const _origGetParameter2 = WebGL2RenderingContext.prototype.getParameter;
      WebGL2RenderingContext.prototype.getParameter = function (param) {
        const ext = this.getExtension('WEBGL_debug_renderer_info');
        if (ext) {
          if (param === ext.UNMASKED_VENDOR_WEBGL) return _fp.webglVendor;
          if (param === ext.UNMASKED_RENDERER_WEBGL) return _fp.webglRenderer;
        }
        return _origGetParameter2.call(this, param);
      };
      _markNative(
        WebGL2RenderingContext.prototype.getParameter,
        'getParameter',
      );
    }

    // -----------------------------------------------------------------
    // 9. Override screen dimensions + devicePixelRatio
    // -----------------------------------------------------------------
    Object.defineProperty(screen, 'width', {
      get: () => _fp.screenWidth,
      configurable: true,
      enumerable: true,
    });
    Object.defineProperty(screen, 'height', {
      get: () => _fp.screenHeight,
      configurable: true,
      enumerable: true,
    });
    Object.defineProperty(screen, 'availWidth', {
      get: () => _fp.screenWidth,
      configurable: true,
      enumerable: true,
    });
    Object.defineProperty(screen, 'availHeight', {
      get: () => _fp.screenHeight - 40, // taskbar offset
      configurable: true,
      enumerable: true,
    });
    Object.defineProperty(window, 'devicePixelRatio', {
      get: () => _fp.devicePixelRatio,
      configurable: true,
      enumerable: true,
    });

    // -----------------------------------------------------------------
    // 10. navigator.oscpu (Firefox only — undefined in Chrome)
    // -----------------------------------------------------------------
    if (_fp.oscpu !== undefined) {
      Object.defineProperty(navigator, 'oscpu', {
        get: () => _fp.oscpu,
        configurable: true,
        enumerable: true,
      });
    }
  }, fp);
}

// ---------------------------------------------------------------------------
// Fingerprint generation
// ---------------------------------------------------------------------------

/**
 * Generate a statistically plausible, internally consistent fingerprint.
 *
 * The fingerprint is based on real browser distributions (Chrome ~60 %,
 * Firefox ~25 %).  All fields are cross-consistent: the UA matches the
 * platform, screen resolution matches a real device, WebGL renderer
 * matches the GPU that device ships with, etc.
 *
 * @returns {import('./profiles.js').BrowserProfile}
 */
export function generateConsistentFingerprint() {
  // Weighted random: 75% Chrome, 25% Firefox (Safari omitted for Playwright).
  const roll = Math.random();
  const browserType = roll < 0.75 ? 'chrome' : 'firefox';
  return getRandomProfile(browserType);
}
